version: '3'

services:
  go:
    build: 
      context: .
    container_name: go-gomicrosvs1
    ports: 
      - "8080:8080"
    depends_on: 
      - "db"
  
  db:
    image: mysql:latest 
    container_name: db-gomicrosvs1 
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment: 
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: db_courses 
    volumes:
      - my-db:/var/lib/mysql
    ports:
      - '53690:3306'
 
volumes: 
  my-db: